%% -*- mode: erlang -*-
%% ex: ft=erlang ts=2 sw=2 et

Mimetypes = [
  {<<".css">>, [<<"text/css">>]},
  {<<".js">>, [<<"application/javascript">>]},
  {<<".html">>, [<<"text/html">>]},
  {<<".txt">>, [<<"text/plain">>]}
],
WWW = {priv_dir, erlvue, [<<"www">>]},
HttpOpts = [{directory, WWW}, {mimetypes, Mimetypes}],

[
  {'_', [
      {"/ping/[...]", erlvue_cb_ping, []},

      {"/", cowboy_static, [{file, <<"index.html">>} | HttpOpts]},
      {"/[...]", cowboy_static, HttpOpts}
    ]}
].
